{
    "CreateLinks": [],
    "OnFailure": "/quickbid/Actions/CreateEntityFailureMessage.action",
    "OnSuccess": "/quickbid/Actions/CreateEntitySuccessMessage.action",
    "Properties": {
        "doc_id": "#Control:doc_id/#SelectedValue",
        "questionnaire_id": "#Control:questionnaire_id/#Value",
        "invitationId": "#Control:invitationId/#Value",
        "description": "#Control:description/#Value",
        "type": "#Control:type/#Value"
    },
    "Target": {
        "EntitySet": "Questionnaire_table",
        "Service": "/quickbid/Services/capoff.service"
    },
    "ActionResult": {
        "_Name": "create"
    },
    "_Type": "Action.Type.ODataService.CreateEntity"
}