{
	"_Type": "Action.Type.ODataService.UpdateEntity",
	"ActionResult": {
		"_Name": "update"
	},
	"OnFailure": "/quickbid/Actions/UpdateEntityFailureMessage.action",
	"OnSuccess": "/quickbid/Actions/UpdateEntitySuccessMessage.action",
	"Target": {
		"EntitySet": "Supplier_bid_table",
		"Service": "/quickbid/Services/capoff.service",
		"ReadLink": "{@odata.readLink}"
	},
	"Properties": {
		"doc_id": "#Control:doc_id/#SelectedValue",
		"invitationId": "#Control:invitationId/#Value",
		"item_id": "#Control:item_id/#Value",
		"title": "#Control:title/#Value",
		"item_name": "#Control:item_name/#Value",
		"supp_quot_price": "#Control:supp_quot_price/#Value",
		"supp_quot_quantity": "#Control:supp_quot_quantity/#Value",
		"price": "#Control:price/#Value",
		"quantity": "#Control:quantity/#Value",
		"status": "#Control:status/#Value",
		"ariba_status": "#Control:ariba_status/#Value",
		"whatsapp_status": "#Control:whatsapp_status/#Value"
	},
	"RequestOptions": {
		"UploadCategory": ""
	}
}