{
    "ModalPageFullscreen": false,
    "ModalPage": true,
    "PageToOpen": "/quickbid/Pages/capoff_Supplier_table/Supplier_table_CreateQuestionnaire_table.page",
    "_Type": "Action.Type.Navigation"
}