{
	"_Type": "Action.Type.ToastMessage",
	"OnSuccess": "/quickbid/Actions/Logging/CloseModalPage_Complete.action",
	"Message": "Entity updated",
	"NumberOfLines": 2,
	"Duration": 2,
	"IsIconHidden": false,
	"Animated": true
}