{
	"_Type": "Action.Type.ProgressBanner",
	"OnSuccess": "/quickbid/Actions/capoff/Service/UploadOffline.action",
	"Message": "Upload in progress...",
	"CompletionMessage": "Sync completed",
	"CompletionTimeout": 4,
	"Animated": true
}